# Generated by Django 5.2.5 on 2026-02-20 05:56

from django.db import migrations


def seed_books(apps, schema_editor):
    Book = apps.get_model("books", "Book")

    sample_books = [
        {
            "title": "Operating Systems",
            "author": "Abraham Silberschatz",
            "isbn": "9781119456339",
            "category": "Computer Science",
            "total_copies": 8,
            "available_copies": 6,
            "published_year": 2018,
        },
        {
            "title": "Database Management Systems",
            "author": "Raghu Ramakrishnan",
            "isbn": "9780072465631",
            "category": "Computer Science",
            "total_copies": 6,
            "available_copies": 4,
            "published_year": 2002,
        },
        {
            "title": "Computer Networks",
            "author": "Andrew S. Tanenbaum",
            "isbn": "9780132126953",
            "category": "Computer Science",
            "total_copies": 7,
            "available_copies": 5,
            "published_year": 2010,
        },
        {
            "title": "Clean Code",
            "author": "Robert C. Martin",
            "isbn": "9780132350884",
            "category": "Software Engineering",
            "total_copies": 5,
            "available_copies": 5,
            "published_year": 2008,
        },
        {
            "title": "Introduction to Algorithms",
            "author": "Thomas H. Cormen",
            "isbn": "9780262046305",
            "category": "Algorithms",
            "total_copies": 4,
            "available_copies": 3,
            "published_year": 2022,
        },
    ]

    for book in sample_books:
        Book.objects.get_or_create(isbn=book["isbn"], defaults=book)


def unseed_books(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    isbns = [
        "9781119456339",
        "9780072465631",
        "9780132126953",
        "9780132350884",
        "9780262046305",
    ]
    Book.objects.filter(isbn__in=isbns).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_books, reverse_code=unseed_books),
    ]
