# Generated by Django 5.2.5 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="allow_digital_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="digital_external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="digital_file",
            field=models.FileField(blank=True, null=True, upload_to="books/digital/"),
        ),
        migrations.AddField(
            model_name="book",
            name="digital_format",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
