# Generated by Django 5.2.5 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_book_digital_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="digital_read_url",
            field=models.URLField(blank=True),
        ),
    ]
