// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtn8L_yc76fmExusjmeZKQfIi2zgWDE_w',
    appId: '1:1077120612242:web:b43468e849487707ed734b',
    messagingSenderId: '1077120612242',
    projectId: 'library-app-b5849',
    authDomain: 'library-app-b5849.firebaseapp.com',
    storageBucket: 'library-app-b5849.firebasestorage.app',
    measurementId: 'G-KYJ0GVBQX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5bh7RN4teD6SAhmkdNc-bTtUCTQPgTA',
    appId: '1:1077120612242:android:214a131480fa66c5ed734b',
    messagingSenderId: '1077120612242',
    projectId: 'library-app-b5849',
    storageBucket: 'library-app-b5849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhaLMEZhM3BIHR3sjVpt72TnpdBnD2qg',
    appId: '1:1077120612242:ios:6235c5ea73f1a110ed734b',
    messagingSenderId: '1077120612242',
    projectId: 'library-app-b5849',
    storageBucket: 'library-app-b5849.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhaLMEZhM3BIHR3sjVpt72TnpdBnD2qg',
    appId: '1:1077120612242:ios:6235c5ea73f1a110ed734b',
    messagingSenderId: '1077120612242',
    projectId: 'library-app-b5849',
    storageBucket: 'library-app-b5849.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtn8L_yc76fmExusjmeZKQfIi2zgWDE_w',
    appId: '1:1077120612242:web:72a5e1e868abdbcbed734b',
    messagingSenderId: '1077120612242',
    projectId: 'library-app-b5849',
    authDomain: 'library-app-b5849.firebaseapp.com',
    storageBucket: 'library-app-b5849.firebasestorage.app',
    measurementId: 'G-C02HZL7888',
  );
}
